### ISSUE TITLE
Uninstall fake news injector

### ISSUE THREAD

**Issue by Sougotsu** [noahc3/fakenews-injector#1]
Hi, Im running kosmos in emunand, but at the beginning of the process I installed the fake news injector.

I'm wondering if I can get banned in the OFW just because exist that fake news, so if its true, how can I remove, uninstall that fake news entry, and launch hekate from the wifi auth method?

**Comment by MindfulProtons** [comment]
I have the same concern here. How do we remove this from the NAND?

**Comment by YamaBanana** [comment]
Well, Factory Reset should do the trick

**Comment by Jabooon** [comment]
So reset factory and erase all game backups or live with it? isnt possible to erase/modify something in NEWS to erase that entry?

**Comment by noahc3** [comment]
603b44dbfd473416e517edb7d6beaf3516c41e09
